### ISSUE TITLE
Akvo FLOW app 2.1.2

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#268]
# Akvo FLOW app v2.1.2

* [x] Release notes
* [x] Test plans:
    - [x] Trailing spaces in option values https://github.com/akvo/akvo-flow-mobile/issues/261#issuecomment-74482477
    - [x] Handle lack of GPS more gracefully https://github.com/akvo/akvo-flow-mobile/issues/262#issuecomment-74496837
    - [x] Confirmation dialog on manual entry https://github.com/akvo/akvo-flow-mobile/issues/236#issuecomment-74700938
    - [x] ANDROID_ID query parameter https://github.com/akvo/akvo-flow-mobile/issues/259#issuecomment-74533088
    - [x] Media files sync https://github.com/akvo/akvo-flow-mobile/issues/96#issuecomment-74649587

* [x] Deploy UAT APK

# FieldSurvey v1.13.8
* [x] Test plan:
    - [x] Trailing spaces in option values https://github.com/akvo/akvo-flow-mobile/issues/261#issuecomment-74482477
* [x] Deploy UAT APK
