### ISSUE TITLE
Akvo FLOW app 2.1.4

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-mobile#284]
* [x] Release notes
* [x] Test plans:
    - [x] Datapoint name truncation https://github.com/akvo/akvo-flow-mobile/issues/278#issuecomment-86905602
    - [x] More explicit error messages https://github.com/akvo/akvo-flow-mobile/issues/276#issuecomment-86479640
    - [x] Bootstrap process fails upon app mismatch [#242]
    
* [x] Deploy UAT APK

**Comment by rumca** [comment]
think we're good to go on Tuesday :+1:
